### ISSUE TITLE
update example ini file

### ISSUE THREAD

**Issue by keiranmraine** [ICGC-TCGA-PanCancer/DEWrapperWorkflow#2]
Hi @denis-yuen, can the DEWorkflowWrapper.ini file be updated to match the docs so that it can be used as a base for the decider templates please.  Mainly to ensure the versions are all in line.

Thanks,
Keiran

**Comment by denis-yuen** [comment]
Updated default in prep for a 1.0.2 release https://github.com/ICGC-TCGA-PanCancer/DEWrapperWorkflow/commit/b984ddc7e4384ea531f5eeb745c8a331981aa350

**Comment by WayneJiao** [comment]
Should this be 1.1 or 1.1.1?

gnosDockerName=pancancer/pancancer_upload_download:1.1.1

it’s 1.1 on the document.
https://github.com/ICGC-TCGA-PanCancer/DEWrapperWorkflow

W

On May 19, 2015, at 1:02 PM, Denis Yuen <notifications@github.com<mailto:notifications@github.com>> wrote:

Updated default in prep for a 1.0.2 release b984ddchttps://github.com/ICGC-TCGA-PanCancer/DEWrapperWorkflow/commit/b984ddc7e4384ea531f5eeb745c8a331981aa350

**Comment by denis-yuen** [comment]
Good catch, it should be 1.1
