### ISSUE TITLE
VCF Uploader parameterization

### ISSUE THREAD

**Issue by niall-byrne** [ICGC-TCGA-PanCancer/DEWrapperWorkflow#8]
The vcf uploader is being incorrectly parameterized for EMBL uploads- it seems it's attempting to pull metadata information from the dst repo, as opposed to the src repo.

During work that pulled data from RIKEN, and then uploaded to DKFZ- the uploader was attempting to pull metadata from DKFZ (where it didn't exist).

**Comment by denis-yuen** [comment]
https://github.com/ICGC-TCGA-PanCancer/DEWrapperWorkflow/commit/8c361c4ff0c43e3dc95a2436490734ad477acb5b
